apiVersion: v1
kind: Pod
metadata:
  name: test-fsgroup-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: test-container
    image: busybox:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - name: test-volume
      mountPath: /data
    securityContext:
      allowPrivilegeEscalation: false
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: test-fsgroup-pvc