apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-fsgroup-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
  resources:
    requests:
      storage: 1Gi