# Copyright (c) 2023 Saglabs SA. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:buster

# Install wget, lsb-release and curl
RUN apt update && \
    apt install -y wget lsb-release curl fuse libfuse3-dev tree ca-certificates e2fsprogs gnupg2 && \
    # security updates
    apt install -y apt systemd

# Add key
RUN wget -O - http://repository.moosefs.com/moosefs.key | apt-key add -
RUN echo "deb http://repository.moosefs.com/3.0.117/apt/debian/buster buster main" > /etc/apt/sources.list.d/moosefs.list

# Install MooseFS client
RUN apt update --allow-releaseinfo-change && apt install -y moosefs-pro-client

# Copy the CSI plugin
ADD moosefs-csi-plugin /bin/

ENTRYPOINT ["/bin/moosefs-csi-plugin"]
