---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: moosefs-block-storage
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: com.tuxera.csi.moosefs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-attacher-runner
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: csi-attacher
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: external-attacher-runner
  apiGroup: rbac.authorization.k8s.io
---
# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: csi-attacher-moosefs-plugin
  namespace: kube-system
  labels:
    app: csi-attacher-moosefs-plugin
spec:
  selector:
    app: csi-attacher-moosefs-plugin
  ports:
    - name: dummy
      port: 12345
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-attacher-moosefs-plugin
  namespace: kube-system
spec:
  serviceName: "csi-attacher-moosefs-plugin"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-attacher-moosefs-plugin
    spec:
      serviceAccount: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v0.2.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: moosefs-csi-plugin
          image: quay.io/tuxera/moosefs-csi-plugin:dev-0.0.4-29
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--topology=$(MFS_TOPOLOGY)"
            - "--aws-access=$(AWS_ACCESS_KEY_ID)"
            - "--aws-secret=$(AWS_SECRET)"
            - "--aws-session=$(AWS_SESSION_TOKEN)"
            - "--aws-region=$(AWS_REGION)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: MFS_TOPOLOGY
              value: "master:AWS,chunk:AWS"
            - name: AWS_ACCESS_KEY_ID
              value: "AWS_ACCESS_KEY_ID"
            - name: AWS_SECRET
              value: "AWS_SECRET"
            - name: AWS_SESSION_TOKEN
              value: "AWS_SESSION_TOKEN"
            - name: AWS_REGION
              value: "eu-west-2"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-provisioner
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-provisioner-runner
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
    
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-role
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: csi-provisioner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: csi-provisioner-moosefs-plugin
  namespace: kube-system
  labels:
    app: csi-provisioner-moosefs-plugin
spec:
  selector:
    app: csi-provisioner-moosefs-plugin
  ports:
    - name: dummy
      port: 12345
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-provisioner-moosefs-plugin
  namespace: kube-system
spec:
  serviceName: "csi-provisioner-moosefs-plugin"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-provisioner-moosefs-plugin
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.2.0
          args:
            - "--provisioner=com.tuxera.csi.moosefs"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: moosefs-csi-plugin
          image: quay.io/tuxera/moosefs-csi-plugin:dev-0.0.4-29
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--topology=$(MFS_TOPOLOGY)"
            - "--aws-access=$(AWS_ACCESS_KEY_ID)"
            - "--aws-secret=$(AWS_SECRET)"
            - "--aws-session=$(AWS_SESSION_TOKEN)"
            - "--aws-region=$(AWS_REGION)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: MFS_TOPOLOGY
              value: "master:AWS,chunk:AWS"
            - name: AWS_ACCESS_KEY_ID
              value: "AWS_ACCESS_KEY_ID"
            - name: AWS_SECRET
              value: "AWS_SECRET"
            - name: AWS_SESSION_TOKEN
              value: "AWS_SESSION_TOKEN"
            - name: AWS_REGION
              value: "eu-west-2"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-moosefs-plugin
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-moosefs-plugin
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-moosefs-plugin
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: csi-moosefs-plugin
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-moosefs-plugin
  apiGroup: rbac.authorization.k8s.io          

---
kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-moosefs-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-moosefs-plugin
  template:
    metadata:
      labels:
        app: csi-moosefs-plugin
    spec:
      serviceAccount: csi-moosefs-plugin
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.2.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
              # TODO(arslan): the registrar is not implemented yet
              # - name: registrar-socket-dir
              #   mountPath: /var/lib/csi/sockets/
        - name: csi-moosefs-plugin 
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/tuxera/moosefs-csi-plugin:dev-0.0.4-29
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--topology=$(MFS_TOPOLOGY)"
            - "--aws-access=$(AWS_ACCESS_KEY_ID)"
            - "--aws-secret=$(AWS_SECRET)"
            - "--aws-session=$(AWS_SESSION_TOKEN)"
            - "--aws-region=$(AWS_REGION)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: MFS_TOPOLOGY
              value: "master:AWS,chunk:AWS"
            - name: AWS_ACCESS_KEY_ID
              value: "AWS_ACCESS_KEY_ID"
            - name: AWS_SECRET
              value: "AWS_SECRET"
            - name: AWS_SESSION_TOKEN
              value: "AWS_SESSION_TOKEN"
            - name: AWS_REGION
              value: "eu-west-2"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              # needed so that any mounts setup inside this container are
              # propagated back to the host machine.
              mountPropagation: "Bidirectional"
            - mountPath: /dev
              name: device-dir
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.tuxera.csi.moosefs
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
